-- Create the api_keys table
create table if not exists public.api_keys (
  id bigint generated by default as identity primary key,
  name text not null,
  key text not null unique,
  status text not null default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.api_keys enable row level security;

-- Create a policy that allows all operations (you can restrict this based on your needs)
create policy "Allow all operations for authenticated users" on public.api_keys
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Grant access to authenticated users
grant all on public.api_keys to authenticated; 